# server {
#     listen 80;
#     server_name localhost;

#     root /usr/share/nginx/html;
#     index index.html;

#     # Proxy API calls to the backend server
#     location /api/ {
#         #proxy_pass http://server:3001;
#         proxy_pass https://interview-mvp-production-9128.up.railway.app;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         client_max_body_size 5m;
#     }

#     # React Router - serve index.html for all non-file routes
#     location / {
#         try_files $uri $uri/ /index.html;
#     }
# }

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://interview-mvp-production-3eef.up.railway.app;

        proxy_set_header Host interview-mvp-production-3eef.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_ssl_server_name on;
        proxy_ssl_name interview-mvp-production-3eef.up.railway.app;

        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;

        client_max_body_size 10m;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}